name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - run: npm ci

      # Build with correct base href for Pages: https://<user>.github.io/<repo>/
      - name: Build Angular
        run: |
          npx ng build --configuration production --base-href "/${{ github.event.repository.name }}/"

      # SPA fallback + disable Jekyll processing (just in case)
      - name: Prepare Pages artifact
        run: |
          cp dist/future-tech/browser/index.html dist/future-tech/browser/404.html
          touch dist/future-tech/browser/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/future-tech/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4